---
title: "R_Activity_Practice"
author: "Dahee Ahn"
date: "2024-09-06"
output: html_document
---
```{r}
rm(list= ls())
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
```

```{r}
iris_df <- read_excel(path="C:/Users/chemk/OneDrive/Desktop/Classes/ENT6707_DataAnalysis/week2/Iris_data_excel.xlsx", sheet="some_famous_data", range= "A1:E151")
```

```{r}
summary(iris_df)
```

```{r}
nrow(iris_df)
```

```{r}
str(iris_df)
```

```{r}
head(iris_df)
```

```{r}
tail(iris_df)
```

```{r}
View(iris_df)
```

```{r}
head(iris_df$Species)
```

```{r}
summary(iris_df$Species)
```

```{r}
is.character(iris_df$Species)
```

```{r}
iris_df$Species <- as.factor(iris_df$Species)
summary(iris_df$Species)
```

```{r}
sepal_greater5 <- iris_df$Sepal.Length > 5
table(sepal_greater5)
```

```{r}
sepal_equal5.1 <- iris_df$Sepal.Length == 5.1
table(sepal_equal5.1)
```

```{r}
x <- 5+5
x
```

```{r}
X <- 5+5; X
```

```{r}
y = 7+3; y
```

```{r}
y==x
```

```{r}
head(iris_df$Sepal.Length %in% c(5.1, 4.6, 6.0))
```

```{r}
head(which(iris_df$Sepal.Length %in% c(5.1, 4.6, 6.0)))
```

```{r}
iris_df[25, 2:3]
iris_df[c(26,31),]
iris_df[,]
iris_df[-5,1:2]
iris_df[which(iris_df$Sepal.Length>5),]
iris_df[which(iris_df$Sepal.Length==5.1),]
```

```{r}
tapply(iris_df$Sepal.Width, iris_df$Species, mean)
```

```{r}
install.packages("tidyverse")
library(tidyverse)
install.packages("conflicted")
library(conflicted)
```

```{r}
iris_df$Species <- as_factor(iris_df$Species)
```

```{r}
iris_df_subset_1 <- iris_df %>% dplyr::filter(Sepal.Length > 5)
summary(iris_df_subset_1)
```

```{r}
iris_df_subset_2 <- dplyr::filter(iris_df, Sepal.Length==5)
summary(iris_df_subset_2)
```

```{r}
species_counts <- table(iris_df_subset_1$Species)
print(species_counts)
```

```{r}
species_counts <- table(iris_df_subset_2$Species)
print(species_counts)
```

```{r}
iris_df %>% group_by(Species) %>% summarise(Means = mean(Sepal.Width), SD = sd(Sepal.Width), max_sep = max(Sepal.Width))
```

```{r}
iris_df %>% group_by(Species) %>% summarise(Means = mean(Sepal.Width), SD = sd(Sepal.Width), max_sep = max(Sepal.Width)) %>% arrange(Means)
```








```{r}
set.seed(123)
iris_df[sample(1:nrow(iris_df),10), "Sepal.Length"]
```

```{r}
tail(is.na(iris_df$Sepal.Length))
```
```{r}
mean(iris_df$"Sepal.Length")
```

```{r}
mean(na.omit(iris_df$"Sepal.Length"))
```

```{r}
mean(iris_df$"Sepal.Length", na.rm=T)
```

```{r}
try1 <- iris_df %>% dplyr::filter(Sepal.Length > mean(Sepal.Length, na.rm = TRUE))
summary(try1)
```

```{r}
set.seed(123)
sample(1:100,3)
```

## R_Activity_Practice_3

```{r}
library(datasets)
head(iris)
```

```{r}
plot(Sepal.Length~Petal.Width, data=iris)
```

```{r}
plot(Sepal.Length~Petal.Width, data=iris, pch=15, col="tomato4", xlab="Width of Petals", ylab="Length of Sepals")
```

```{r}
library("tidyverse")
library("ggplot2")
```

```{r}
ggplot(data=iris, mapping=aes(x=Petal.Width, y=Sepal.Length, col=Species)) + geom_point()
```

```{r}
ggplot(iris, mapping=aes(x=Petal.Width, y=Sepal.Length)) + geom_point(shape=15, col="tomato4")
```

```{r}
ggplot(iris, mapping=aes(x=Petal.Width, y=Sepal.Length, col=Species, shape=Species)) + geom_point()
```

```{r}
ggplot(iris, mapping=aes(x=Petal.Width, y=Sepal.Length, col=Species, shape=Species))+geom_point()+theme_classic()
```

```{r}
ggplot(iris, mapping=aes(x=Petal.Width, y=Sepal.Length, col=Species, shape=Species))+geom_point()+theme_classic()+theme(legend.position=c(0.2,0.8), legend.title=element_blank())
```

```{r}
ggplot(iris, mapping=aes(x=Petal.Width, y=Sepal.Length, col=Species, shape=Species))+geom_point()+theme_classic()+xlab("Petal width (cm)")+ylab("Sepal length (cm)")+theme(legend.position="none")
```

```{r}
ggplot(iris, mapping=aes(x=Petal.Width))+geom_histogram(color="purple", fill="pink")+theme_classic()+theme(legend.position="none")
```

```{r}
ggplot(iris, mapping=aes(x=Species, y=Petal.Width, fill=Species))+geom_boxplot()+theme_classic()+scale_fill_manual(values=c("pink","purple","red"))+theme(legend.position="none")
```

```{r}
library(datasets)
library(tidyverse)
library(dplyr)
```

```{r}
iris_t <- iris %>% dplyr::filter(Species == c("versicolor", "virginica"))
boxplot(Sepal.Length~Species, data=iris_t)
```


```{r}
library(dplyr)
iris_t <- iris %>% dplyr::filter(Species == c("versicolor", "virginica")) %>% droplevels()
boxplot(Sepal.Length~Species, data = iris_t)
stripchart(Sepal.Length~Species, data = iris_t, pch = 19, add = TRUE, vertical = TRUE, method = "jitter", jitter = 0.2)
```

```{r}
hist(iris$Sepal.Length)
```

```{r}
qqnorm(iris$Sepal.Length)
```

```{r}
var_check <- iris_t %>% group_by(Species) %>% summarise(Variance = var(Sepal.Length))
var_check$Variance[2]/var_check$Variance[1]
```

```{r}
group1 <- iris_t$Sepal.Length[iris_t$Species == "versicolor"]
group2 <- iris_t$Sepal.Length[iris_t$Species == "virginica"]
t.test(group1, group2, alternative = "two.sided", paired=F, var.equal=T)
```
```{r}
install.packages("plotrix")
library(plotrix)
iris_t %>% group_by(Species) %>% summarise(means = round(mean(Sepal.Length),2), SE = round(std.error(Sepal.Length),2))
```

```{r}
t.test(Sepal.Length~Species, data=iris_t, alternative = "two.sided", var.equal=T)
```

##R Activity 5
```{r}
ggplot(iris, mapping=aes(y=Sepal.Length, x=Species, fill=Species))+geom_boxplot()+theme_classic()+xlab("Species")+ylab("Sepal Length")
```

```{r}
fit_1 <- lm(Sepal.Length~Species, data=iris)
anova(fit_1)
```

```{r}
plot(fit_1, which=c(2))
```
##The errors
```{r}
plot(fit_1, which=c(1))
```

```{r}
fit_1_log <- lm(log(Sepal.Length)~Species, data=iris)
plot(fit_1_log, which=c(2))
```

```{r}
plot(fit_1_log, which=c(1))
```

```{r}
install.packages("emmeans")
library(emmeans)
emmeans(fit_1, pairwise~Species)
```
```{r}
install.packages("multcomp")
library(multcomp)
tukey_fit_1 <- glht(fit_1, linfct=mcp(Species="Tukey"))
summary(tukey_fit_1)
```

```{r}
library(plotrix) #for std.error function
```

```{r}
iris %>% group_by(Species) %>% summarise(means = mean(Sepal.Length), SE = std.error(Sepal.Length))
```

## Chi-squared analysis
```{r}
iris$size <- ifelse(iris$Sepal.Length < median(iris$Sepal.Length), "small", "big")
table(iris$Species, iris$size)
ggplot(iris)+aes(x=Species, fill=size)+geom_bar()+theme_bw()
chisq_test_1 <- chisq.test(table(iris$Species, iris$size))
chisq_test_1
install.packages("corrplot")
library(corrplot)
chisq_test_1
corrplot(chisq_test_1$residuals, is.cor = FALSE)
```
## Linear Models - refer to R_Activity_Assignment_4
```{r}
summary(pigs)
```

